version: '2'
services:
  web:
    build: ./docker/apache
    ports:
      - "80:80"
    volumes:
      - .:/var/www
      - ./public:/var/www/html
    links:
      - db

  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - /var/lib/mysql
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_USER=app
      - MYSQL_PASSWORD=password
